spring:
  datasource:
    url : jdbc:postgresql://localhost:5556/Should-i-Bunk
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.postgreSLDialect

app:
  security:
    jwt:
      access-token-expiration: 8640000
      refresh-token-expiration: 604800000
